

services:

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "3002:3002"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - frontend
      - user-service
      - product-service
