events {}

http {

    server {

        listen 80;

        location / {
            proxy_pass http://frontend:3000;
        }

        location /users/ {
            proxy_pass http://user-service:3001/;
        }

        location /products/ {
            proxy_pass http://product-service:3002/;
        }
    }
}
